import org.jnativehook.keyboard.NativeKeyEvent
import java.awt.event.KeyEvent

enum class Key(val keyEvent: Int, val nativeKeyEvent: Int): Condition {
    N0(KeyEvent.VK_0, NativeKeyEvent.VC_0),
    N1(KeyEvent.VK_1, NativeKeyEvent.VC_1),
    N2(KeyEvent.VK_2, NativeKeyEvent.VC_2),
    N3(KeyEvent.VK_3, NativeKeyEvent.VC_3),
    N4(KeyEvent.VK_4, NativeKeyEvent.VC_4),
    N5(KeyEvent.VK_5, NativeKeyEvent.VC_5),
    N6(KeyEvent.VK_6, NativeKeyEvent.VC_6),
    N7(KeyEvent.VK_7, NativeKeyEvent.VC_7),
    N8(KeyEvent.VK_8, NativeKeyEvent.VC_8),
    N9(KeyEvent.VK_9, NativeKeyEvent.VC_9),

    A(KeyEvent.VK_A, NativeKeyEvent.VC_A),
    B(KeyEvent.VK_B, NativeKeyEvent.VC_B),
    C(KeyEvent.VK_C, NativeKeyEvent.VC_C),
    D(KeyEvent.VK_D, NativeKeyEvent.VC_D),
    E(KeyEvent.VK_E, NativeKeyEvent.VC_E),
    F(KeyEvent.VK_F, NativeKeyEvent.VC_F),
    G(KeyEvent.VK_G, NativeKeyEvent.VC_G),
    H(KeyEvent.VK_H, NativeKeyEvent.VC_H),
    I(KeyEvent.VK_I, NativeKeyEvent.VC_I),
    J(KeyEvent.VK_J, NativeKeyEvent.VC_J),
    K(KeyEvent.VK_K, NativeKeyEvent.VC_K),
    L(KeyEvent.VK_L, NativeKeyEvent.VC_L),
    M(KeyEvent.VK_M, NativeKeyEvent.VC_M),
    N(KeyEvent.VK_N, NativeKeyEvent.VC_N),
    O(KeyEvent.VK_O, NativeKeyEvent.VC_O),
    P(KeyEvent.VK_P, NativeKeyEvent.VC_P),
    Q(KeyEvent.VK_Q, NativeKeyEvent.VC_Q),
    R(KeyEvent.VK_R, NativeKeyEvent.VC_R),
    S(KeyEvent.VK_S, NativeKeyEvent.VC_S),
    T(KeyEvent.VK_T, NativeKeyEvent.VC_T),
    U(KeyEvent.VK_U, NativeKeyEvent.VC_U),
    V(KeyEvent.VK_V, NativeKeyEvent.VC_V),
    W(KeyEvent.VK_W, NativeKeyEvent.VC_W),
    X(KeyEvent.VK_X, NativeKeyEvent.VC_X),
    Y(KeyEvent.VK_Y, NativeKeyEvent.VC_Y),
    Z(KeyEvent.VK_Z, NativeKeyEvent.VC_Z),

    F1(KeyEvent.VK_F1, NativeKeyEvent.VC_F1),
    F2(KeyEvent.VK_F2, NativeKeyEvent.VC_F2),
    F3(KeyEvent.VK_F3, NativeKeyEvent.VC_F3),
    F4(KeyEvent.VK_F4, NativeKeyEvent.VC_F4),
    F5(KeyEvent.VK_F5, NativeKeyEvent.VC_F5),
    F6(KeyEvent.VK_F6, NativeKeyEvent.VC_F6),
    F7(KeyEvent.VK_F7, NativeKeyEvent.VC_F7),
    F8(KeyEvent.VK_F8, NativeKeyEvent.VC_F8),
    F9(KeyEvent.VK_F9, NativeKeyEvent.VC_F9),
    F10(KeyEvent.VK_F10, NativeKeyEvent.VC_F10),
    F11(KeyEvent.VK_F11, NativeKeyEvent.VC_F11),
    F12(KeyEvent.VK_F12, NativeKeyEvent.VC_F12),
    F13(KeyEvent.VK_F13, NativeKeyEvent.VC_F13),
    F14(KeyEvent.VK_F14, NativeKeyEvent.VC_F14),
    F15(KeyEvent.VK_F15, NativeKeyEvent.VC_F15),
    F16(KeyEvent.VK_F16, NativeKeyEvent.VC_F16),
    F17(KeyEvent.VK_F17, NativeKeyEvent.VC_F17),
    F18(KeyEvent.VK_F18, NativeKeyEvent.VC_F18),
    F19(KeyEvent.VK_F19, NativeKeyEvent.VC_F19),
    F20(KeyEvent.VK_F20, NativeKeyEvent.VC_F20),
    F21(KeyEvent.VK_F21, NativeKeyEvent.VC_F21),
    F22(KeyEvent.VK_F22, NativeKeyEvent.VC_F22),
    F23(KeyEvent.VK_F23, NativeKeyEvent.VC_F23),
    F24(KeyEvent.VK_F24, NativeKeyEvent.VC_F24),

    UP(KeyEvent.VK_UP, NativeKeyEvent.VC_UP),
    LEFT(KeyEvent.VK_LEFT, NativeKeyEvent.VC_LEFT),
    RIGHT(KeyEvent.VK_RIGHT, NativeKeyEvent.VC_RIGHT),
    DOWN(KeyEvent.VK_DOWN, NativeKeyEvent.VC_DOWN),

    CTRL(KeyEvent.VK_CONTROL, NativeKeyEvent.VC_CONTROL),
    ALT(KeyEvent.VK_ALT, NativeKeyEvent.VC_ALT),
    SHIFT(KeyEvent.VK_SHIFT, NativeKeyEvent.VC_SHIFT),
    ESCAPE(KeyEvent.VK_ESCAPE, NativeKeyEvent.VC_ESCAPE),
    META(KeyEvent.VK_META, NativeKeyEvent.VC_META),
    CAPS_LOCK(KeyEvent.VK_CAPS_LOCK, NativeKeyEvent.VC_CAPS_LOCK),

    ENTER(KeyEvent.VK_ENTER, NativeKeyEvent.VC_ENTER),
    SPACE(KeyEvent.VK_SPACE, NativeKeyEvent.VC_SPACE),
    TAB(KeyEvent.VK_TAB, NativeKeyEvent.VC_TAB),

    COMMA(KeyEvent.VK_COMMA, NativeKeyEvent.VC_COMMA),
    PERIOD(KeyEvent.VK_PERIOD, NativeKeyEvent.VC_PERIOD),
    MINUS(KeyEvent.VK_MINUS, NativeKeyEvent.VC_MINUS),
    EQUALS(KeyEvent.VK_EQUALS, NativeKeyEvent.VC_EQUALS),
    SEMICOLON(KeyEvent.VK_SEMICOLON, NativeKeyEvent.VC_SEMICOLON),
    BACKSPACE(KeyEvent.VK_BACK_SPACE, NativeKeyEvent.VC_BACKSPACE),
    UNDERSCORE(KeyEvent.VK_UNDERSCORE, NativeKeyEvent.VC_UNDERSCORE),
    SLASH(KeyEvent.VK_SLASH, NativeKeyEvent.VC_SLASH),
    BACK_SLASH(KeyEvent.VK_BACK_SLASH, NativeKeyEvent.VC_BACK_SLASH),
    OPEN_BRACKET(KeyEvent.VK_OPEN_BRACKET, NativeKeyEvent.VC_OPEN_BRACKET),
    CLOSE_BRACKET(KeyEvent.VK_CLOSE_BRACKET, NativeKeyEvent.VC_CLOSE_BRACKET),
    QUOTE(KeyEvent.VK_QUOTE, NativeKeyEvent.VC_QUOTE),
    BACK_QUOTE(KeyEvent.VK_BACK_QUOTE, NativeKeyEvent.VC_BACKQUOTE),

    PRINTSCREEN(KeyEvent.VK_PRINTSCREEN, NativeKeyEvent.VC_PRINTSCREEN),
    SCROLL_LOCK(KeyEvent.VK_SCROLL_LOCK, NativeKeyEvent.VC_SCROLL_LOCK),
    NUM_LOCK(KeyEvent.VK_NUM_LOCK, NativeKeyEvent.VC_NUM_LOCK),

    INSERT(KeyEvent.VK_INSERT, NativeKeyEvent.VC_INSERT),
    DELETE(KeyEvent.VK_DELETE, NativeKeyEvent.VC_DELETE),
    HOME(KeyEvent.VK_HOME, NativeKeyEvent.VC_HOME),
    END(KeyEvent.VK_END, NativeKeyEvent.VC_END),
    PAGE_UP(KeyEvent.VK_PAGE_UP, NativeKeyEvent.VC_PAGE_UP),
    PAGE_DOWN(KeyEvent.VK_PAGE_DOWN, NativeKeyEvent.VC_PAGE_DOWN),

    PAUSE(KeyEvent.VK_PAUSE, NativeKeyEvent.VC_PAUSE),
    CLEAR(KeyEvent.VK_CLEAR, NativeKeyEvent.VC_CLEAR),

    SEPARATOR(KeyEvent.VK_SEPARATOR, NativeKeyEvent.VC_SEPARATOR),
    CONTEXT_MENU(KeyEvent.VK_CONTEXT_MENU, NativeKeyEvent.VC_CONTEXT_MENU),
//    POWER(KeyEvent.VK_POWER, NativeKeyEvent.VC_POWER),
//    SLEEP(KeyEvent.VK_SLEEP, NativeKeyEvent.VC_SLEEP),
//    WAKE(KeyEvent.VK_WAKE, NativeKeyEvent.VC_WAKE),
//    MEDIA_PLAY(KeyEvent.VK_MEDIA_PLAY, NativeKeyEvent.VC_MEDIA_PLAY),
//    MEDIA_STOP(KeyEvent.VK_MEDIA_STOP, NativeKeyEvent.VC_MEDIA_STOP),
//    MEDIA_PREVIOUS(KeyEvent.VK_MEDIA_PREVIOUS, NativeKeyEvent.VC_MEDIA_PREVIOUS),
//    MEDIA_NEXT(KeyEvent.VK_MEDIA_NEXT, NativeKeyEvent.VC_MEDIA_NEXT),
//    MEDIA_SELECT(KeyEvent.VK_MEDIA_SELECT, NativeKeyEvent.VC_MEDIA_SELECT),
//    MEDIA_EJECT(KeyEvent.VK_MEDIA_EJECT, NativeKeyEvent.VC_MEDIA_EJECT),
//    VOLUME_MUTE(KeyEvent.VK_VOLUME_MUTE, NativeKeyEvent.VC_VOLUME_MUTE),
//    VOLUME_UP(KeyEvent.VK_VOLUME_UP, NativeKeyEvent.VC_VOLUME_UP),
//    VOLUME_DOWN(KeyEvent.VK_VOLUME_DOWN, NativeKeyEvent.VC_VOLUME_DOWN),
//    APP_MAIL(KeyEvent.VK_APP_MAIL, NativeKeyEvent.VC_APP_MAIL),
//    APP_CALCULATOR(KeyEvent.VK_APP_CALCULATOR, NativeKeyEvent.VC_APP_CALCULATOR),
//    APP_MUSIC(KeyEvent.VK_APP_MUSIC, NativeKeyEvent.VC_APP_MUSIC),
//    APP_PICTURES(KeyEvent.VK_APP_PICTURES, NativeKeyEvent.VC_APP_PICTURES),
//    BROWSER_SEARCH(KeyEvent.VK_BROWSER_SEARCH, NativeKeyEvent.VC_BROWSER_SEARCH),
//    BROWSER_HOME(KeyEvent.VK_BROWSER_HOME, NativeKeyEvent.VC_BROWSER_HOME),
//    BROWSER_BACK(KeyEvent.VK_BROWSER_BACK, NativeKeyEvent.VC_BROWSER_BACK),
//    BROWSER_FORWARD(KeyEvent.VK_BROWSER_FORWARD, NativeKeyEvent.VC_BROWSER_FORWARD),
//    BROWSER_STOP(KeyEvent.VK_BROWSER_STOP, NativeKeyEvent.VC_BROWSER_STOP),
//    BROWSER_REFRESH(KeyEvent.VK_BROWSER_REFRESH, NativeKeyEvent.VC_BROWSER_REFRESH),
//    BROWSER_FAVORITES(KeyEvent.VK_BROWSER_FAVORITES, NativeKeyEvent.VC_BROWSER_FAVORITES),
//    FURIGANA(KeyEvent.VK_FURIGANA, NativeKeyEvent.VC_FURIGANA),
    KATAKANA(KeyEvent.VK_KATAKANA, NativeKeyEvent.VC_KATAKANA),
    KANJI(KeyEvent.VK_KANJI, NativeKeyEvent.VC_KANJI),
    HIRAGANA(KeyEvent.VK_HIRAGANA, NativeKeyEvent.VC_HIRAGANA),
//    YEN(KeyEvent.VK_YEN, NativeKeyEvent.VC_YEN),
//    SUN_HELP(KeyEvent.VK_SUN_HELP, NativeKeyEvent.VC_SUN_HELP),
//    SUN_STOP(KeyEvent.VK_SUN_STOP, NativeKeyEvent.VC_SUN_STOP),
//    SUN_PROPS(KeyEvent.VK_SUN_PROPS, NativeKeyEvent.VC_SUN_PROPS),
//    SUN_FRONT(KeyEvent.VK_SUN_FRONT, NativeKeyEvent.VC_SUN_FRONT),
//    SUN_OPEN(KeyEvent.VK_SUN_OPEN, NativeKeyEvent.VC_SUN_OPEN),
//    SUN_FIND(KeyEvent.VK_SUN_FIND, NativeKeyEvent.VC_SUN_FIND),
//    SUN_AGAIN(KeyEvent.VK_SUN_AGAIN, NativeKeyEvent.VC_SUN_AGAIN),
//    SUN_UNDO(KeyEvent.VK_SUN_UNDO, NativeKeyEvent.VC_SUN_UNDO),
//    SUN_COPY(KeyEvent.VK_SUN_COPY, NativeKeyEvent.VC_SUN_COPY),
//    SUN_INSERT(KeyEvent.VK_SUN_INSERT, NativeKeyEvent.VC_SUN_INSERT),
//    SUN_CUT(KeyEvent.VK_SUN_CUT, NativeKeyEvent.VC_SUN_CUT),
    UNDEFINED(KeyEvent.VK_UNDEFINED, NativeKeyEvent.VC_UNDEFINED),;

//    operator fun plus(shift: Key): Any {
//        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
//    }

}

fun NativeKeyEvent.toKey(): Key {
    return Key.values().first { key ->
        key.nativeKeyEvent == this.keyCode
    }
}

